"""empty message

Revision ID: 04acdf0deda6
Revises: 
Create Date: 2019-03-26 17:20:44.369006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04acdf0deda6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=130), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(length=400), nullable=True),
    sa.Column('picture', sa.Text(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('max_failed_login', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_message_read'), 'messages', ['message_read'], unique=False)
    op.create_index(op.f('ix_messages_subject'), 'messages', ['subject'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('tutorial', sa.String(length=10000), nullable=True),
    sa.Column('video', sa.String(length=220), nullable=True),
    sa.Column('item_list', sa.String(length=10000), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_edit', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_created_date'), 'projects', ['created_date'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_last_edit'), 'projects', ['last_edit'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_username'), 'projects', ['username'], unique=False)
    op.create_table('last_visit',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('last_visit_date', sa.DateTime(), nullable=True),
    sa.Column('initial_visit_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('photo_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('photoOne', sa.String(length=500), nullable=True),
    sa.Column('photoTwo', sa.String(length=500), nullable=True),
    sa.Column('photoThree', sa.String(length=500), nullable=True),
    sa.Column('photoFour', sa.String(length=500), nullable=True),
    sa.Column('photoFive', sa.String(length=500), nullable=True),
    sa.Column('photoSix', sa.String(length=500), nullable=True),
    sa.Column('photoSeven', sa.String(length=500), nullable=True),
    sa.Column('photoEight', sa.String(length=500), nullable=True),
    sa.Column('photoNine', sa.String(length=500), nullable=True),
    sa.Column('photoTen', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_gallery_title'), 'photo_gallery', ['title'], unique=False)
    op.create_table('project_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_comments_timestamp'), 'project_comments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_project_comments_title'), 'project_comments', ['title'], unique=False)
    op.create_index(op.f('ix_project_comments_username'), 'project_comments', ['username'], unique=False)
    op.create_table('project_likers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('comment_likers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['project_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_table('comment_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('reply', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_comment_id'], ['project_comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_replies_timestamp'), 'comment_replies', ['timestamp'], unique=False)
    op.create_index(op.f('ix_comment_replies_title'), 'comment_replies', ['title'], unique=False)
    op.create_index(op.f('ix_comment_replies_username'), 'comment_replies', ['username'], unique=False)
    op.create_table('reply_likers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['comment_replies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_likers')
    op.drop_index(op.f('ix_comment_replies_username'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_title'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_timestamp'), table_name='comment_replies')
    op.drop_table('comment_replies')
    op.drop_table('comment_likers')
    op.drop_table('project_likers')
    op.drop_index(op.f('ix_project_comments_username'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_title'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_timestamp'), table_name='project_comments')
    op.drop_table('project_comments')
    op.drop_index(op.f('ix_photo_gallery_title'), table_name='photo_gallery')
    op.drop_table('photo_gallery')
    op.drop_table('last_visit')
    op.drop_index(op.f('ix_projects_username'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_last_edit'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_date'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_subject'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_read'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('followers')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
