"""empty message

Revision ID: 1679fdaf7af6
Revises: 16baecdd8db6
Create Date: 2019-04-11 00:45:26.558487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1679fdaf7af6'
down_revision = '16baecdd8db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('maintenance_enabled', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('tutorial_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'tutorial_enabled')
    op.drop_column('projects', 'maintenance_enabled')
    # ### end Alembic commands ###
