"""empty message

Revision ID: 16baecdd8db6
Revises: b2a23adbbebe
Create Date: 2019-04-10 23:32:15.228266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16baecdd8db6'
down_revision = 'b2a23adbbebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('itemlist_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'itemlist_enabled')
    # ### end Alembic commands ###
