"""empty message

Revision ID: 3b462f714714
Revises: ad600e672a11
Create Date: 2019-04-08 15:52:48.848096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b462f714714'
down_revision = 'ad600e672a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itemlist', sa.Column('itemlink', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itemlist', 'itemlink')
    # ### end Alembic commands ###
