"""empty message

Revision ID: 6032c2610a09
Revises: 77fcf972e2b0
Create Date: 2019-04-12 17:08:06.993754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6032c2610a09'
down_revision = '77fcf972e2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('comment_note', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('msg_note', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('reply_note', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reply_note')
    op.drop_column('user', 'msg_note')
    op.drop_column('user', 'comment_note')
    # ### end Alembic commands ###
