"""empty message

Revision ID: 70c095658658
Revises: 3b462f714714
Create Date: 2019-04-09 13:41:01.426385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c095658658'
down_revision = '3b462f714714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('aquariums', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('carnivorous', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('desert', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('enclosedtropical', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('freshwater', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('opentropical', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('plantsonly', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('reptiles', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('saltwater', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('terrariums', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('vivariumpaludarium', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('waterreptiles', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_projects_aquariums'), 'projects', ['aquariums'], unique=False)
    op.create_index(op.f('ix_projects_carnivorous'), 'projects', ['carnivorous'], unique=False)
    op.create_index(op.f('ix_projects_desert'), 'projects', ['desert'], unique=False)
    op.create_index(op.f('ix_projects_enclosedtropical'), 'projects', ['enclosedtropical'], unique=False)
    op.create_index(op.f('ix_projects_freshwater'), 'projects', ['freshwater'], unique=False)
    op.create_index(op.f('ix_projects_opentropical'), 'projects', ['opentropical'], unique=False)
    op.create_index(op.f('ix_projects_plantsonly'), 'projects', ['plantsonly'], unique=False)
    op.create_index(op.f('ix_projects_reptiles'), 'projects', ['reptiles'], unique=False)
    op.create_index(op.f('ix_projects_saltwater'), 'projects', ['saltwater'], unique=False)
    op.create_index(op.f('ix_projects_terrariums'), 'projects', ['terrariums'], unique=False)
    op.create_index(op.f('ix_projects_vivariumpaludarium'), 'projects', ['vivariumpaludarium'], unique=False)
    op.create_index(op.f('ix_projects_waterreptiles'), 'projects', ['waterreptiles'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_waterreptiles'), table_name='projects')
    op.drop_index(op.f('ix_projects_vivariumpaludarium'), table_name='projects')
    op.drop_index(op.f('ix_projects_terrariums'), table_name='projects')
    op.drop_index(op.f('ix_projects_saltwater'), table_name='projects')
    op.drop_index(op.f('ix_projects_reptiles'), table_name='projects')
    op.drop_index(op.f('ix_projects_plantsonly'), table_name='projects')
    op.drop_index(op.f('ix_projects_opentropical'), table_name='projects')
    op.drop_index(op.f('ix_projects_freshwater'), table_name='projects')
    op.drop_index(op.f('ix_projects_enclosedtropical'), table_name='projects')
    op.drop_index(op.f('ix_projects_desert'), table_name='projects')
    op.drop_index(op.f('ix_projects_carnivorous'), table_name='projects')
    op.drop_index(op.f('ix_projects_aquariums'), table_name='projects')
    op.drop_column('projects', 'waterreptiles')
    op.drop_column('projects', 'vivariumpaludarium')
    op.drop_column('projects', 'terrariums')
    op.drop_column('projects', 'saltwater')
    op.drop_column('projects', 'reptiles')
    op.drop_column('projects', 'plantsonly')
    op.drop_column('projects', 'opentropical')
    op.drop_column('projects', 'freshwater')
    op.drop_column('projects', 'enclosedtropical')
    op.drop_column('projects', 'desert')
    op.drop_column('projects', 'carnivorous')
    op.drop_column('projects', 'aquariums')
    # ### end Alembic commands ###
