"""empty message

Revision ID: 8e489827d6d6
Revises: 1ab4981823d0
Create Date: 2019-03-31 23:11:15.003976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e489827d6d6'
down_revision = '1ab4981823d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_title'), 'notifications', ['title'], unique=False)
    op.create_index(op.f('ix_notifications_username'), 'notifications', ['username'], unique=False)
    op.add_column('projects', sa.Column('commentsAndReplies_last_read', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('private', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_projects_commentsAndReplies_last_read'), 'projects', ['commentsAndReplies_last_read'], unique=False)
    op.create_index(op.f('ix_projects_private'), 'projects', ['private'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_private'), table_name='projects')
    op.drop_index(op.f('ix_projects_commentsAndReplies_last_read'), table_name='projects')
    op.drop_column('projects', 'private')
    op.drop_column('projects', 'commentsAndReplies_last_read')
    op.drop_index(op.f('ix_notifications_username'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_title'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
