"""empty message

Revision ID: ba77c17af049
Revises: daa204315a85
Create Date: 2019-04-20 23:50:59.002241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba77c17af049'
down_revision = 'daa204315a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('avatar', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'avatar')
    # ### end Alembic commands ###
