"""empty message

Revision ID: ca1870a0de9d
Revises: 
Create Date: 2019-06-05 21:39:40.811284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1870a0de9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('avatar', sa.String(length=200), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_message_read'), 'chat_history', ['message_read'], unique=False)
    op.create_index(op.f('ix_chat_history_room'), 'chat_history', ['room'], unique=False)
    op.create_index(op.f('ix_chat_history_timestamp'), 'chat_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_history_username'), 'chat_history', ['username'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('firstname', sa.String(length=30), nullable=True),
    sa.Column('lastname', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=130), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.Text(length=400), nullable=True),
    sa.Column('picture', sa.Text(length=500), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('max_failed_login', sa.Integer(), nullable=True),
    sa.Column('subscription', sa.String(length=20), nullable=True),
    sa.Column('msg_note', sa.Boolean(), nullable=True),
    sa.Column('comment_note', sa.Boolean(), nullable=True),
    sa.Column('reply_note', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=50), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('blocked_users',
    sa.Column('blocker_id', sa.Integer(), nullable=True),
    sa.Column('blocked_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blocked_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['user.id'], )
    )
    op.create_table('chatlist_favorites',
    sa.Column('fav_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('body', sa.String(length=1500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_message_read'), 'messages', ['message_read'], unique=False)
    op.create_index(op.f('ix_messages_subject'), 'messages', ['subject'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('data', sa.String(length=150), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_timestamp'), 'notifications', ['timestamp'], unique=False)
    op.create_index(op.f('ix_notifications_title'), 'notifications', ['title'], unique=False)
    op.create_index(op.f('ix_notifications_username'), 'notifications', ['username'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('itemlist_enabled', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('tutorial', sa.Text(length=100000), nullable=True),
    sa.Column('tutorial_enabled', sa.Boolean(), nullable=True),
    sa.Column('maintenance', sa.Text(length=100000), nullable=True),
    sa.Column('maintenance_enabled', sa.Boolean(), nullable=True),
    sa.Column('video', sa.String(length=220), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('last_edit', sa.DateTime(), nullable=True),
    sa.Column('last_update_type', sa.String(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('private', sa.Boolean(), nullable=True),
    sa.Column('aquariums', sa.Boolean(), nullable=True),
    sa.Column('saltwater', sa.Boolean(), nullable=True),
    sa.Column('freshwater', sa.Boolean(), nullable=True),
    sa.Column('terrariums', sa.Boolean(), nullable=True),
    sa.Column('enclosedtropical', sa.Boolean(), nullable=True),
    sa.Column('opentropical', sa.Boolean(), nullable=True),
    sa.Column('carnivorous', sa.Boolean(), nullable=True),
    sa.Column('desert', sa.Boolean(), nullable=True),
    sa.Column('reptiles', sa.Boolean(), nullable=True),
    sa.Column('vivariumpaludarium', sa.Boolean(), nullable=True),
    sa.Column('waterreptiles', sa.Boolean(), nullable=True),
    sa.Column('plantsonly', sa.Boolean(), nullable=True),
    sa.Column('commentsAndReplies_last_read', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_aquariums'), 'projects', ['aquariums'], unique=False)
    op.create_index(op.f('ix_projects_carnivorous'), 'projects', ['carnivorous'], unique=False)
    op.create_index(op.f('ix_projects_commentsAndReplies_last_read'), 'projects', ['commentsAndReplies_last_read'], unique=False)
    op.create_index(op.f('ix_projects_created_date'), 'projects', ['created_date'], unique=False)
    op.create_index(op.f('ix_projects_description'), 'projects', ['description'], unique=False)
    op.create_index(op.f('ix_projects_desert'), 'projects', ['desert'], unique=False)
    op.create_index(op.f('ix_projects_enclosedtropical'), 'projects', ['enclosedtropical'], unique=False)
    op.create_index(op.f('ix_projects_freshwater'), 'projects', ['freshwater'], unique=False)
    op.create_index(op.f('ix_projects_last_edit'), 'projects', ['last_edit'], unique=False)
    op.create_index(op.f('ix_projects_last_update_type'), 'projects', ['last_update_type'], unique=False)
    op.create_index(op.f('ix_projects_opentropical'), 'projects', ['opentropical'], unique=False)
    op.create_index(op.f('ix_projects_plantsonly'), 'projects', ['plantsonly'], unique=False)
    op.create_index(op.f('ix_projects_private'), 'projects', ['private'], unique=False)
    op.create_index(op.f('ix_projects_reptiles'), 'projects', ['reptiles'], unique=False)
    op.create_index(op.f('ix_projects_saltwater'), 'projects', ['saltwater'], unique=False)
    op.create_index(op.f('ix_projects_terrariums'), 'projects', ['terrariums'], unique=False)
    op.create_index(op.f('ix_projects_title'), 'projects', ['title'], unique=False)
    op.create_index(op.f('ix_projects_username'), 'projects', ['username'], unique=False)
    op.create_index(op.f('ix_projects_vivariumpaludarium'), 'projects', ['vivariumpaludarium'], unique=False)
    op.create_index(op.f('ix_projects_waterreptiles'), 'projects', ['waterreptiles'], unique=False)
    op.create_table('FAQs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('faqenabled', sa.Boolean(), nullable=True),
    sa.Column('question1', sa.String(length=200), nullable=True),
    sa.Column('answer1', sa.String(length=500), nullable=True),
    sa.Column('enabled1', sa.Boolean(), nullable=True),
    sa.Column('question2', sa.String(length=200), nullable=True),
    sa.Column('answer2', sa.String(length=500), nullable=True),
    sa.Column('enabled2', sa.Boolean(), nullable=True),
    sa.Column('question3', sa.String(length=200), nullable=True),
    sa.Column('answer3', sa.String(length=500), nullable=True),
    sa.Column('enabled3', sa.Boolean(), nullable=True),
    sa.Column('question4', sa.String(length=200), nullable=True),
    sa.Column('answer4', sa.String(length=500), nullable=True),
    sa.Column('enabled4', sa.Boolean(), nullable=True),
    sa.Column('question5', sa.String(length=200), nullable=True),
    sa.Column('answer5', sa.String(length=500), nullable=True),
    sa.Column('enabled5', sa.Boolean(), nullable=True),
    sa.Column('question6', sa.String(length=200), nullable=True),
    sa.Column('answer6', sa.String(length=500), nullable=True),
    sa.Column('enabled6', sa.Boolean(), nullable=True),
    sa.Column('question7', sa.String(length=200), nullable=True),
    sa.Column('answer7', sa.String(length=500), nullable=True),
    sa.Column('enabled7', sa.Boolean(), nullable=True),
    sa.Column('question8', sa.String(length=200), nullable=True),
    sa.Column('answer8', sa.String(length=500), nullable=True),
    sa.Column('enabled8', sa.Boolean(), nullable=True),
    sa.Column('question9', sa.String(length=200), nullable=True),
    sa.Column('answer9', sa.String(length=500), nullable=True),
    sa.Column('enabled9', sa.Boolean(), nullable=True),
    sa.Column('question10', sa.String(length=200), nullable=True),
    sa.Column('answer10', sa.String(length=500), nullable=True),
    sa.Column('enabled10', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_FAQs_answer1'), 'FAQs', ['answer1'], unique=False)
    op.create_index(op.f('ix_FAQs_answer10'), 'FAQs', ['answer10'], unique=False)
    op.create_index(op.f('ix_FAQs_answer2'), 'FAQs', ['answer2'], unique=False)
    op.create_index(op.f('ix_FAQs_answer3'), 'FAQs', ['answer3'], unique=False)
    op.create_index(op.f('ix_FAQs_answer4'), 'FAQs', ['answer4'], unique=False)
    op.create_index(op.f('ix_FAQs_answer5'), 'FAQs', ['answer5'], unique=False)
    op.create_index(op.f('ix_FAQs_answer6'), 'FAQs', ['answer6'], unique=False)
    op.create_index(op.f('ix_FAQs_answer7'), 'FAQs', ['answer7'], unique=False)
    op.create_index(op.f('ix_FAQs_answer8'), 'FAQs', ['answer8'], unique=False)
    op.create_index(op.f('ix_FAQs_answer9'), 'FAQs', ['answer9'], unique=False)
    op.create_index(op.f('ix_FAQs_faqenabled'), 'FAQs', ['faqenabled'], unique=False)
    op.create_index(op.f('ix_FAQs_question1'), 'FAQs', ['question1'], unique=False)
    op.create_index(op.f('ix_FAQs_question10'), 'FAQs', ['question10'], unique=False)
    op.create_index(op.f('ix_FAQs_question2'), 'FAQs', ['question2'], unique=False)
    op.create_index(op.f('ix_FAQs_question3'), 'FAQs', ['question3'], unique=False)
    op.create_index(op.f('ix_FAQs_question4'), 'FAQs', ['question4'], unique=False)
    op.create_index(op.f('ix_FAQs_question5'), 'FAQs', ['question5'], unique=False)
    op.create_index(op.f('ix_FAQs_question6'), 'FAQs', ['question6'], unique=False)
    op.create_index(op.f('ix_FAQs_question7'), 'FAQs', ['question7'], unique=False)
    op.create_index(op.f('ix_FAQs_question8'), 'FAQs', ['question8'], unique=False)
    op.create_index(op.f('ix_FAQs_question9'), 'FAQs', ['question9'], unique=False)
    op.create_index(op.f('ix_FAQs_title'), 'FAQs', ['title'], unique=False)
    op.create_index(op.f('ix_FAQs_username'), 'FAQs', ['username'], unique=False)
    op.create_table('deleted_messages',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('itemlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=40), nullable=True),
    sa.Column('itemname', sa.String(length=100), nullable=True),
    sa.Column('itemlink', sa.String(length=1500), nullable=True),
    sa.Column('itembrand', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=250), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itemlist_title'), 'itemlist', ['title'], unique=False)
    op.create_index(op.f('ix_itemlist_username'), 'itemlist', ['username'], unique=False)
    op.create_table('photo_gallery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('photoOne', sa.String(length=500), nullable=True),
    sa.Column('photoTwo', sa.String(length=500), nullable=True),
    sa.Column('photoThree', sa.String(length=500), nullable=True),
    sa.Column('photoFour', sa.String(length=500), nullable=True),
    sa.Column('photoFive', sa.String(length=500), nullable=True),
    sa.Column('photoSix', sa.String(length=500), nullable=True),
    sa.Column('photoSeven', sa.String(length=500), nullable=True),
    sa.Column('photoEight', sa.String(length=500), nullable=True),
    sa.Column('photoNine', sa.String(length=500), nullable=True),
    sa.Column('photoTen', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_gallery_title'), 'photo_gallery', ['title'], unique=False)
    op.create_table('project_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('comment', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_comments_timestamp'), 'project_comments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_project_comments_title'), 'project_comments', ['title'], unique=False)
    op.create_index(op.f('ix_project_comments_username'), 'project_comments', ['username'], unique=False)
    op.create_table('project_likers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('project_visitors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('last_visit_date', sa.DateTime(), nullable=True),
    sa.Column('initial_visit_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('comment_likers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['project_comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'comment_id')
    )
    op.create_table('comment_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('reply', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('project_comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_comment_id'], ['project_comments.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_replies_timestamp'), 'comment_replies', ['timestamp'], unique=False)
    op.create_index(op.f('ix_comment_replies_title'), 'comment_replies', ['title'], unique=False)
    op.create_index(op.f('ix_comment_replies_username'), 'comment_replies', ['username'], unique=False)
    op.create_table('reply_likers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reply_id'], ['comment_replies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'reply_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_likers')
    op.drop_index(op.f('ix_comment_replies_username'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_title'), table_name='comment_replies')
    op.drop_index(op.f('ix_comment_replies_timestamp'), table_name='comment_replies')
    op.drop_table('comment_replies')
    op.drop_table('comment_likers')
    op.drop_table('project_visitors')
    op.drop_table('project_likers')
    op.drop_index(op.f('ix_project_comments_username'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_title'), table_name='project_comments')
    op.drop_index(op.f('ix_project_comments_timestamp'), table_name='project_comments')
    op.drop_table('project_comments')
    op.drop_index(op.f('ix_photo_gallery_title'), table_name='photo_gallery')
    op.drop_table('photo_gallery')
    op.drop_index(op.f('ix_itemlist_username'), table_name='itemlist')
    op.drop_index(op.f('ix_itemlist_title'), table_name='itemlist')
    op.drop_table('itemlist')
    op.drop_table('deleted_messages')
    op.drop_index(op.f('ix_FAQs_username'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_title'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question9'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question8'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question7'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question6'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question5'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question4'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question3'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question2'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question10'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_question1'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_faqenabled'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer9'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer8'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer7'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer6'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer5'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer4'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer3'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer2'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer10'), table_name='FAQs')
    op.drop_index(op.f('ix_FAQs_answer1'), table_name='FAQs')
    op.drop_table('FAQs')
    op.drop_index(op.f('ix_projects_waterreptiles'), table_name='projects')
    op.drop_index(op.f('ix_projects_vivariumpaludarium'), table_name='projects')
    op.drop_index(op.f('ix_projects_username'), table_name='projects')
    op.drop_index(op.f('ix_projects_title'), table_name='projects')
    op.drop_index(op.f('ix_projects_terrariums'), table_name='projects')
    op.drop_index(op.f('ix_projects_saltwater'), table_name='projects')
    op.drop_index(op.f('ix_projects_reptiles'), table_name='projects')
    op.drop_index(op.f('ix_projects_private'), table_name='projects')
    op.drop_index(op.f('ix_projects_plantsonly'), table_name='projects')
    op.drop_index(op.f('ix_projects_opentropical'), table_name='projects')
    op.drop_index(op.f('ix_projects_last_update_type'), table_name='projects')
    op.drop_index(op.f('ix_projects_last_edit'), table_name='projects')
    op.drop_index(op.f('ix_projects_freshwater'), table_name='projects')
    op.drop_index(op.f('ix_projects_enclosedtropical'), table_name='projects')
    op.drop_index(op.f('ix_projects_desert'), table_name='projects')
    op.drop_index(op.f('ix_projects_description'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_date'), table_name='projects')
    op.drop_index(op.f('ix_projects_commentsAndReplies_last_read'), table_name='projects')
    op.drop_index(op.f('ix_projects_carnivorous'), table_name='projects')
    op.drop_index(op.f('ix_projects_aquariums'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_username'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_title'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_timestamp'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_subject'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_read'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('followers')
    op.drop_table('chatlist_favorites')
    op.drop_table('blocked_users')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_chat_history_username'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_timestamp'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_room'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_message_read'), table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
