"""empty message

Revision ID: d008be47c3be
Revises: ba77c17af049
Create Date: 2019-04-21 14:23:18.658589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd008be47c3be'
down_revision = 'ba77c17af049'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('online', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'online')
    # ### end Alembic commands ###
