"""empty message

Revision ID: daa204315a85
Revises: 4f3c0cd1942b
Create Date: 2019-04-20 23:36:30.621154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa204315a85'
down_revision = '4f3c0cd1942b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('message_read', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_history_message_read'), 'chat_history', ['message_read'], unique=False)
    op.create_index(op.f('ix_chat_history_room'), 'chat_history', ['room'], unique=False)
    op.create_index(op.f('ix_chat_history_timestamp'), 'chat_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_history_username'), 'chat_history', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_username'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_timestamp'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_room'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_message_read'), table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
